export const SET_BEVERAGES = 'SET_BEVERAGES';
export const FETCH_BEVERAGES_FAILED = 'FETCH_BEVERAGES_FAILED';

export const ADD_BEVERAGE = 'ADD_BEVERAGE';
export const REMOVE_BEVERAGE = 'REMOVE_BEVERAGE';